#############################################################################
# Makefile for building: SourceAdminTool.app/Contents/MacOS/SourceAdminTool
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  SourceAdminTool.pro
# Template: app
# Command: /Users/Drifter/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SourceAdminTool.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt/5.4/clang_64/mkspecs/macx-clang -F/Users/Drifter/Qt/5.4/clang_64/lib
QMAKE         = /Users/Drifter/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SourceAdminTool1.0.0
DISTDIR = /Users/Drifter/Documents/sat/.tmp/SourceAdminTool1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Drifter/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Drifter/Qt/5.4/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		query.cpp \
		serverinfo.cpp \
		settings.cpp \
		worker.cpp \
		customitems.cpp \
		rcon.cpp \
		simplecrypt.cpp \
		main_events.cpp \
		main_slots.cpp \
		rcon_slots.cpp \
		query_slots.cpp qrc_icons.cpp \
		moc_mainwindow.cpp \
		moc_query.cpp \
		moc_worker.cpp \
		moc_rcon.cpp
OBJECTS       = main.o \
		mainwindow.o \
		query.o \
		serverinfo.o \
		settings.o \
		worker.o \
		customitems.o \
		rcon.o \
		simplecrypt.o \
		main_events.o \
		main_slots.o \
		rcon_slots.o \
		query_slots.o \
		qrc_icons.o \
		moc_mainwindow.o \
		moc_query.o \
		moc_worker.o \
		moc_rcon.o
DIST          = ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		SourceAdminTool.pro mainwindow.h \
		query.h \
		serverinfo.h \
		settings.h \
		worker.h \
		customitems.h \
		rcon.h \
		simplecrypt.h \
		ui_mainwindow.h main.cpp \
		mainwindow.cpp \
		query.cpp \
		serverinfo.cpp \
		settings.cpp \
		worker.cpp \
		customitems.cpp \
		rcon.cpp \
		simplecrypt.cpp \
		main_events.cpp \
		main_slots.cpp \
		rcon_slots.cpp \
		query_slots.cpp
QMAKE_TARGET  = SourceAdminTool
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SourceAdminTool.app/Contents/MacOS/SourceAdminTool

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d SourceAdminTool.app/Contents/MacOS/ || mkdir -p SourceAdminTool.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SourceAdminTool.pro ../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		SourceAdminTool.pro \
		icons.qrc \
		/Users/Drifter/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Drifter/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Drifter/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/Drifter/Qt/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SourceAdminTool.pro
../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
SourceAdminTool.pro:
icons.qrc:
/Users/Drifter/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Drifter/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Drifter/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/Drifter/Qt/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SourceAdminTool.pro

qmake_all: FORCE

SourceAdminTool.app/Contents/PkgInfo: 
	@test -d SourceAdminTool.app/Contents || mkdir -p SourceAdminTool.app/Contents
	@$(DEL_FILE) SourceAdminTool.app/Contents/PkgInfo
	@echo "APPL????" >SourceAdminTool.app/Contents/PkgInfo
SourceAdminTool.app/Contents/Resources/empty.lproj: 
	@test -d SourceAdminTool.app/Contents/Resources || mkdir -p SourceAdminTool.app/Contents/Resources
	@touch SourceAdminTool.app/Contents/Resources/empty.lproj
	
SourceAdminTool.app/Contents/Info.plist: 
	@test -d SourceAdminTool.app/Contents || mkdir -p SourceAdminTool.app/Contents
	@$(DEL_FILE) SourceAdminTool.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,a.SourceAdminTool,g" -e "s,@ICON@,sourceadmin.rc,g" -e "s,@EXECUTABLE@,SourceAdminTool,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >SourceAdminTool.app/Contents/Info.plist
SourceAdminTool.app/Contents/Resources/sourceadmin.rc: sourceadmin.rc
	@test -d SourceAdminTool.app/Contents/Resources/ || mkdir -p SourceAdminTool.app/Contents/Resources/
	@$(DEL_FILE) SourceAdminTool.app/Contents/Resources/sourceadmin.rc
	@$(COPY_FILE) sourceadmin.rc SourceAdminTool.app/Contents/Resources/sourceadmin.rc

all: Makefile \
		SourceAdminTool.app/Contents/PkgInfo \
		SourceAdminTool.app/Contents/Resources/empty.lproj \
		SourceAdminTool.app/Contents/Info.plist \
		SourceAdminTool.app/Contents/Resources/sourceadmin.rc $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h query.h serverinfo.h settings.h worker.h customitems.h rcon.h simplecrypt.h ui_mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp query.cpp serverinfo.cpp settings.cpp worker.cpp customitems.cpp rcon.cpp simplecrypt.cpp main_events.cpp main_slots.cpp rcon_slots.cpp query_slots.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r SourceAdminTool.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/csgo.png \
		icons/cstrike.gif \
		icons/css.png \
		icons/fortressforever.gif \
		icons/alienswarm.png \
		icons/garrysmod.png \
		icons/hl2.gif \
		icons/zps.gif \
		icons/rust.png \
		icons/ark.png \
		icons/dod.png \
		icons/vac.png \
		icons/czero.gif \
		icons/lock.png \
		icons/tf2.png \
		icons/l4d.png \
		icons/dota2.png \
		icons/l4d2.gif \
		icons/cspromod.png \
		icons/nucleardawn.png \
		icons/tfc.png \
		icons/dods.png \
		icons/insurgency.gif
	/Users/Drifter/Qt/5.4/clang_64/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_query.cpp moc_worker.cpp moc_rcon.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_query.cpp moc_worker.cpp moc_rcon.cpp
moc_mainwindow.cpp: ../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		mainwindow.h
	/Users/Drifter/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Drifter/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/Drifter/Documents/sat -I/Users/Drifter/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/Drifter/Qt/5.4/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_query.cpp: serverinfo.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		query.h
	/Users/Drifter/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Drifter/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/Drifter/Documents/sat -I/Users/Drifter/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/Drifter/Qt/5.4/clang_64/lib query.h -o moc_query.cpp

moc_worker.cpp: ../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		worker.h
	/Users/Drifter/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Drifter/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/Drifter/Documents/sat -I/Users/Drifter/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/Drifter/Qt/5.4/clang_64/lib worker.h -o moc_worker.cpp

moc_rcon.cpp: ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		rcon.h
	/Users/Drifter/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Drifter/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/Drifter/Documents/sat -I/Users/Drifter/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/Drifter/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/Drifter/Qt/5.4/clang_64/lib rcon.h -o moc_rcon.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/Drifter/Qt/5.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStyleFactory \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QPalette \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp ui_mainwindow.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		settings.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

query.o: query.cpp query.h \
		serverinfo.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		worker.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o query.o query.cpp

serverinfo.o: serverinfo.cpp serverinfo.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		query.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverinfo.o serverinfo.cpp

settings.o: settings.cpp settings.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		ui_mainwindow.h \
		simplecrypt.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFlags \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

worker.o: worker.cpp worker.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		query.h \
		serverinfo.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o worker.cpp

customitems.o: customitems.cpp customitems.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customitems.o customitems.cpp

rcon.o: rcon.cpp rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		serverinfo.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		worker.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rcon.o rcon.cpp

simplecrypt.o: simplecrypt.cpp simplecrypt.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFlags \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCryptographicHash \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcryptographichash.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDataStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatastream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplecrypt.o simplecrypt.cpp

main_events.o: main_events.cpp ui_mainwindow.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_events.o main_events.cpp

main_slots.o: main_slots.cpp ui_mainwindow.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		worker.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QInputDialog \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_slots.o main_slots.cpp

rcon_slots.o: rcon_slots.cpp ui_mainwindow.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rcon_slots.o rcon_slots.cpp

query_slots.o: query_slots.cpp ui_mainwindow.h \
		mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QHostAddress \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		query.h \
		serverinfo.h \
		rcon.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QUdpSocket \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		customitems.h \
		worker.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o query_slots.o query_slots.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_query.o: moc_query.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_query.o moc_query.cpp

moc_worker.o: moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worker.o moc_worker.cpp

moc_rcon.o: moc_rcon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rcon.o moc_rcon.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

